#
# File: services.yml
# Description: Restart vagrant services
#
---

- hosts: "*"

  #
  # Variables
  #
  vars:
    - app_env: 'prod'
    - app_root_dir: '/var/www/casebox-admin'

  #
  # Tasks
  #
  tasks:
    - name: "APP | Update Admin UI sources."
      shell: "cd {{ app_root_dir }}/; git pull origin master;"
      become: yes

    - name: "APP | Fix files permissions."
      shell: "chown vagrant:vagrant {{ app_root_dir }}/ -R"
      become: yes

    - name: "APP | Composer update."
      shell: "composer update --working-dir={{ app_root_dir }}/"

    - name: "APP | Clear cache."
      shell: "php {{ app_root_dir }}/bin/console ca:cl --env={{ app_env }}"

    - name: "APP | Add Admin UI assests."
      shell: "php {{ app_root_dir }}/bin/console assets:install --relative --symlink {{ app_root_dir }}/web --env={{ app_env }}"

    - name: "APP | Crear previous sessions."
      shell: "rm -r {{ app_root_dir }}/var/sessions/prod"
      become: yes

    - name: "APP | Fix permissions."
      shell: "chmod 0777 -R {{ app_root_dir }}/{{ item }}"
      with_items:
        - 'var/cache'
        - 'var/logs'
        - 'var/database'
        - 'var/sessions'
      become: yes

    - name: "APP | Stop dashboard webserver."
      shell: "php {{ app_root_dir }}/bin/console server:stop 0.0.0.0:8000 --env={{ app_env }}"
      ignore_errors: yes
      become: yes

    - name: "APP | Run dashboard webserver."
      shell: "php {{ app_root_dir }}/bin/console server:start 0.0.0.0:8000 --env={{ app_env }}"
      ignore_errors: yes
      become: yes

    - name: "APP | Stop queue."
      shell: "php {{ app_root_dir }}/bin/console app:queue:stop"
      ignore_errors: yes
      become: yes

    - name: "APP | Run queue in background."
      shell: "php {{ app_root_dir }}/bin/console app:queue:start"
      ignore_errors: yes
      become: yes
